#cloud-config
package_upgrade: true
packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
write_files:
  - path: /usr/local/bin/add-docker-users.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      for u in $(getent group sudo | awk -F: '{print $4}' | tr ',' ' ');
        do sudo adduser $u docker > /dev/null;
      done
runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - curl -fsSL https://get.docker.com/ | sh
  - /usr/local/bin/add-docker-users.sh
